# FastStats (https://faststats.dev) collects anonymous usage statistics for plugin developers.
# This helps developers understand how their projects are used in the real world.
#
# No IP addresses, player data, or personal information is collected.
# The server ID below is randomly generated and can be regenerated at any time.
#
# Enabling metrics has no noticeable performance impact.
# Keeping metrics enabled is recommended, but you can opt out by setting
# 'enabled=false' in plugins/faststats/config.properties.
#
# If you suspect a plugin is collecting personal data or bypassing the "enabled" option,
# please report it at: https://faststats.dev/abuse
#
# For more information, visit: https://faststats.dev/info
#
#Thu May 28 10:25:38 UTC 2026
debug=false
enabled=true
serverId=13ea7823-94cb-4eef-a5f3-d6869bc7bbe8
submitAdditionalMetrics=true
submitErrors=true
